### ISSUE TITLE
Contact and FAQ Page Content

### ISSUE THREAD

**Issue by JorgeRicardoSantanaLora** [Jorisanlo27/Universidad-ProyectoFinalGrupo3#17]
Por favor @CNelson29, carga el diseño de la pagina de Contact y FAQ. 

Colocale a la rama el nombre de: 
-**wip-contact-faq-pages-content**

Recuerden:
-Crear una rama para trabajar en esto utilizando la nomenclatura que les comente (wip-nombredelafuncionalidad), en la parte de abajo a la derecha de esta página. (create branch)
-En Visual Studia, hacer fetch.
-Luego checkout de la rama. (entrar en la rama creada)

Cuando terminen:
-Guardar los cambios, pasarlos al stage area y por ultimo hacer los commits.

Cuando Termines de todo:
-Hacer pull request.

**Comment by Jorisanlo27** [comment]
@CNelson29 cargame los cambios que no se han subido
