### ISSUE TITLE
Diseño de la pagina principal Dashboard y Faculties

### ISSUE THREAD

**Issue by Jorisanlo27** [Jorisanlo27/Universidad-ProyectoFinalGrupo3#8]
Por favor equipo de front-end, luego de haber elegido la plantilla de bootstrap que utilizaremos, empezar con el diseño de la pagina princial (Home) y @CNelson29 carga el diseño de la pagina de faculties.

Recuerden:

- Crear una rama para trabajar en esto utilizando la nomenclatura que les comente (wip-nombredelafuncionalidad), en la parte de abajo a la derecha de esta página. (create branch)
- En Visual Studia, hacer fetch.
- Luego checkout de la rama. (entrar en la rama creada)

Cuando terminen:

- Guardar los cambios, pasarlos al stage area y por ultimo hacer los commits.

Cuando Todos Terminen:

- Hacer pull request.

**Comment by CNelson29** [comment]
Ya hice el commit y sincronicé los cambios.
En espera...
